export const INIT_BASE_DATA = 'INIT_BASE_DATA';

export const INIT_FORM_DATA= 'INIT_FORM_DATA'

export const CHANGE_FORM_DATA = 'CHANGE_FORM_DATA'

export const INIT_TABLE_DATA = 'INIT_TABLE_DATA'

export const TABLE_VALUE_CHANGE = 'TABLE_VALUE_CHANGE'


export const TABLE_ALL_FLUSH = 'TABLE_ALL_FLUSH'

export const TABLE_TOP_VALUE_CHANGE = 'TABLE_TOP_VALUE_CHANGE'

export const TABLE_MID_VALUE_CHANGE = 'TABLE_MID_VALUE_CHANGE'

export const TABLE_BOTTOM_VALUE_CHANGE = 'TABLE_BOTTOM_VALUE_CHANGE'

export const INIT_EQUIPMENT_DATA = 'INIT_EQUIPMENT_DATA'

export const TABLE_DEV_VALUE_CHANGE = 'TABLE_DEV_VALUE_CHANGE'

export const INIT_HISTORY_DATA = 'INIT_HISTORY_DATA'

